### ISSUE TITLE
Terraform crashes when creating "outscale_api_access_policy"  resource

### ISSUE THREAD

**Issue by outscale-mzi** [outscale-dev/terraform-provider-outscale#166]
Hello,

When testing the PR: Implement secure environment https://github.com/outscale-dev/terraform-provider-outscale/pull/153 , I found the following issue:

### Terraform Version
```
Terraform v1.0.6
```

### Terraform Configuration Files

```
resource "outscale_ca" "my_first_ca" {
  ca_pem      = file("terraform/terraform-ca-certificate.pem.crt")
}

resource "outscale_api_access_rule" "AAR-2" {
  ca_ids = [outscale_ca.my_first_ca.ca_id]
 }

resource "outscale_api_access_policy" "policy-1" {
  max_access_key_expiration_seconds = 3153600000
  require_trusted_env  = true
depends_on = [outscale_api_access_rule.AAR-2]
}
```

### Debug Output
```
Terraform will perform the following actions:

  # outscale_api_access_policy.policy-1 will be created
  + resource "outscale_api_access_policy" "policy-1" {
      + id                                = (known after apply)
      + max_access_key_expiration_seconds = 3153600000
      + request_id                        = (known after apply)
      + require_trusted_env               = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

outscale_api_access_policy.policy-1: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with outscale_api_access_policy.policy-1,
│   on APIAccessPolicy.tf line 9, in resource "outscale_api_access_policy" "policy-1":
│    9: resource "outscale_api_access_policy" "policy-1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

### Crash Output
```
Stack trace from the terraform-provider-outscale_v0.0.0-secure-env-3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19b7432]

goroutine 12 [running]:
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0006610e0, 0xc0007f9a90, 0xc000b00a60, 0x1db0640, 0xc00009ffe8, 0x1e48001, 0xc000699a18, 0xc00038cc30)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/schema/resource.go:320 +0x352
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000ba480, 0xc000a41a38, 0xc0007f9a90, 0xc000b00a60, 0xc0002b8088, 0xc00080a420, 0x1e4a020)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00011aab0, 0x229e510, 0xc000adb710, 0xc000b06ee0, 0xc00011aab0, 0xc000adb710, 0xc000173ba0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.1/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1f86a80, 0xc00011aab0, 0x229e510, 0xc000adb710, 0xc00068ec00, 0x0, 0x229e510, 0xc000adb710, 0xc0006de0f0, 0xe1)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.1/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003536c0, 0x22a7e38, 0xc00016a600, 0xc000122700, 0xc000144570, 0x2a7ca00, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003536c0, 0x22a7e38, 0xc00016a600, 0xc000122700, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000036500, 0xc0003536c0, 0x22a7e38, 0xc00016a600, 0xc000122700)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-outscale_v0.0.0-secure-env-3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
The resource "outscale_api_access_policy"  is created correctly.

### Actual Behavior
terraform crashes.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by outscale-mzi** [comment]
Hello @outscale-toa  :) 
Issue fixed by @outscale-toa
[fix api access policy](https://github.com/outscale-toa/terraform-provider-outscale/commit/80b658dad35f68a18888a7678aa4b00911fcdfcf)
[80b658d](https://github.com/outscale-toa/terraform-provider-outscale/commit/80b658dad35f68a18888a7678aa4b00911fcdfcf) 

Thanks!
