### ISSUE TITLE
Trying to terraform apply/refresh with deleted VPX makes TF crash

### ISSUE THREAD

**Issue by jerome-jutteau** [outscale-dev/terraform-provider-outscale#18]
# (Imported Issue)

had a tfstate that mentioned a VPC Peering with name "monitoring-peering-landingzone".

As expected, Terraform did this request:

2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 2021/04/13 16:14:55 
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: POST /api/v1/ReadNetPeerings HTTP/1.1
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Host: api.cloudgouv-eu-west-1.outscale.com
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: User-Agent: terraform-provider-outscale-dev
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Content-Length: 61
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Accept: application/json
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Content-Type: application/json
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Accept-Encoding: gzip
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 
2021-04-13T16:14:55.278Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: {"Filters":{"TagValues":["monitoring-peering-landingzone"]}}
However, the VPC Peering did not existed, and Terraform crashed:

2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: -----------------------------------------------------
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 2021/04/13 16:14:55 
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: HTTP/1.1 200 OK
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Content-Length: 89
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Access-Control-Allow-Origin: *
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Content-Type: application/json
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Date: Tue, 13 Apr 2021 16:14:55 GMT
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Referrer-Policy: same-origin
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Server: api-gw/0
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: Strict-Transport-Security: max-age=31536000; includeSubdomains;
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: X-Content-Type-Options: nosniff
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: X-Frame-Options: SAMEORIGIN
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: X-Xss-Protection: 1; mode=block
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 
2021-04-13T16:14:55.407Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: {"NetPeerings":[],"ResponseContext":{"RequestId":"XXX"}}
2021-04-13T16:14:55.409Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: panic: runtime error: index out of range [0] with length 0
2021-04-13T16:14:55.409Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 
2021-04-13T16:14:55.409Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: goroutine 41 [running]:
2021-04-13T16:14:55.409Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: github.com/terraform-providers/terraform-provider-outscale/outscale.dataSourceOutscaleOAPILinPeeringConnectionRead(0xc0002dc1c0, 0x113e9c0, 0xc00018a1c8, 0xc0002dc1c0, 0x0)
2021-04-13T16:14:55.409Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	github.com/terraform-providers/terraform-provider-outscale/outscale/data_source_outscale_net_peering.go:91 +0x1792
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc0001da900, 0xc0002d0a00, 0x113e9c0, 0xc00018a1c8, 0xc0001aa958, 0x1, 0x0)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:403 +0x88
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000114080, 0xc000553ad0, 0xc0002d0a00, 0xc0002d0a00, 0x0, 0x0)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/provider.go:451 +0x8f
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e008, 0x155cba0, 0xc0004b04b0, 0xc0003dca00, 0xc00000e008, 0xc0004b04b0, 0xc000597b78)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/helper/plugin/grpc_provider.go:1036 +0x42d
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x133b320, 0xc00000e008, 0x155cba0, 0xc0004b04b0, 0xc00041cfc0, 0x0, 0x155cba0, 0xc0004b04b0, 0xc00012a2c0, 0xa4)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/tfplugin5/tfplugin5.pb.go:3341 +0x214
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001c80, 0x15669e0, 0xc000195200, 0xc0000d5d00, 0xc000519230, 0x1cc0fd0, 0x0, 0x0, 0x0)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: google.golang.org/grpc.(*Server).handleStream(0xc000001c80, 0x15669e0, 0xc000195200, 0xc0000d5d00, 0x0)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003d2320, 0xc000001c80, 0x15669e0, 0xc000195200, 0xc0000d5d00)
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-13T16:14:55.410Z [DEBUG] plugin.terraform-provider-outscale_v0.2.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
Can you please handle the case where the API does not return a resource that is expected by tfstate to display an error instead of crash ?

Thanks

**Comment by outscale-toa** [comment]
Done in v0.3.0 
In ChangeLog: 
- terraform crash when "outscale_net_peering" resource cannot be found (TPD-1943)
