### ISSUE TITLE
Plugin did not respond

### ISSUE THREAD

**Issue by sylvain987** [outscale-dev/terraform-provider-outscale#265]
### Terraform Version
```
0.6.0 and 0.7.0
```

### Terraform Configuration Files
```terraform
...
```

### Crash Output
```
│ Error: Plugin did not respond
│
│   with module.VM["AXWAY-AZb-GTW-M2"].outscale_volume.DISK-APPLI[0],
│   on ../../module-vm/main.tf line 69, in resource "outscale_volume" "DISK-APPLI":
│   69: resource "outscale_volume" "DISK-APPLI" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-outscale_v0.7.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 157 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.resourceOAPIVolumeRead(0xc0005dee70, {0xfe7be0?, 0xc000a981a8?})
        github.com/terraform-providers/terraform-provider-outscale/outscale/resource_outscale_volume.go:221 +0x4bf
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00021c460, 0xc00079bd60, {0xfe7be0, 0xc000a981a8})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00020cba0, {0xc00097b200?, 0x4ba886?}, 0xc00097b200)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/internal/helper/plugin/grpc_provider.go:535 +0x365
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x119cba0?, 0xc00020cba0}, {0x15068b0, 0xc0007444b0}, 0xc00097b1a0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001de380, {0x150aec0, 0xc000270480}, 0xc000cbe000, 0xc00001a5a0, 0x1d13670, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xcab
google.golang.org/grpc.(*Server).handleStream(0xc0001de380, {0x150aec0, 0xc000270480}, 0xc000cbe000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-outscale_v0.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
Plan OK

### Actual Behavior
Plan KO with errors

### Steps to Reproduce
```
terraform init
terraform plan -out=main.tfplan
```

### Additional Context
After a manual deletion of VM and disk, there is the error. But normally, Terraform would recreate the resources. For example, if I make a new plan with the deletion of state, it's OK. Terraform want recreate the resource.

**Comment by FredericBerot-Armand** [comment]
Hi @sylvain987,

Thanks for find this issue, i do a PR for fix this.

Have a good day !

**Comment by sylvain987** [comment]
Hello,

Thank you for the reply. Do you know when you will release this patch ?

Regards.

**Comment by FredericBerot-Armand** [comment]
Probably at the end of January, =/
But it'll merge this week, so you can build manually when this issue will be closed. ^^

Regards
